# Generated by Django 2.2.2 on 2020-03-10 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20200309_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='approve_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
